### PR TITLE
Removed http dependency to fix issue #10

### PR DESCRIPTION
**Pull request by okrplay**
I implemented the StatusCode using an enum. The status codes are later assigned a number via a HashMap.

### CODE REVIEW

**Comment by NullSense** [comment]
Make sure to tag the git commits when bumping the version as well. For the future please write your git messages in the *imperative*, as stated in the [A note about git commit messages article](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) and CONTRIBUTING.

**Comment by NullSense** [comment]
@okrplay could you update the ContentType to use a HashMap as well, so that the code is more consistent? It also looks like there are a few unresolved conflicts. Thanks for the contribution.

**Comment by okrplay** [comment]
> 
> 
> @okrplay could you update the ContentType to use a HashMap as well, so that the code is more consistent? It also looks like there are a few unresolved conflicts. Thanks for the contribution.

On it.

**Review by NullSense — APPROVED** [review]

**Comment by NullSense** [comment]
@okrplay any ideas why the checks aren't completing?

**Comment by okrplay** [comment]
Apparently you need to [configure an extra event](https://help.github.com/en/articles/events-that-trigger-workflows) for pull requests, I didn't know you'd have to do this either.

**Comment by NullSense** [comment]
Thanks for the contribution @okrplay , have  a good HacktoberFest.

**Comment by okrplay** [comment]
Thanks, you too! 👍

**Pull request merged**
